# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  workflow_dispatch:

defaults:
  run:
    working-directory: ./deploying-exercises/expressjs-cors/backend

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Cleanup deploying-exercises/expressjs-cors
        working-directory: ./deploying-exercises/expressjs-cors
        run: |
          ls -la .
          rm -rf * || true
          ls -la .
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: deploying-exercises/expressjs-cors/backend/package-lock.json
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
      - name: Clean old logs of backend
        continue-on-error: true
        run: pm2 flush backend
      - name: Restart the process on each new deploy or start the process if it does not exist
        run: pm2 restart backend || pm2 start index.js --name backend
